Repository termkit/gama, pull requests merged in 2024-03, with the labels that each got.

#42 Sort workflow as alphabetical
  internal/terminal/handler/ghworkflow/ghworkflow.go
Labels: improvement

#44 Feature #9: Make bool work like option/choice
  internal/terminal/handler/ghtrigger/ghtrigger.go
  pkg/workflow/workflow.go
Labels: improvement

#43 Small improvements
  internal/terminal/handler/handler.go
  internal/terminal/handler/information/information.go
  internal/version/repository/ports.go
  internal/version/repository/repository.go
  internal/version/repository/repository_test.go
  internal/version/usecase/ports.go
  internal/version/usecase/usecase.go
Labels: improvement

#48 Improve the logic
  internal/terminal/handler/ghtrigger/ghtrigger.go
Labels: bug, Important

#51 Feature #49: Custom keys mapping
  config.yaml
  internal/terminal/handler/ghrepository/keymap.go
  internal/terminal/handler/ghtrigger/keymap.go
  internal/terminal/handler/ghworkflow/keymap.go
  internal/terminal/handler/ghworkflowhistory/keymap.go
  internal/terminal/handler/information/keymap.go
  internal/terminal/handler/keymap.go
  pkg/config/config.go
  pkg/config/shortcuts.go
Labels: feature

#52 Use new configuration path
  Dockerfile
  README.md
  config.yaml
  pkg/config/config.go
Labels: improvement

#53 Add sha256 summary support
  .github/workflows/release.yaml
  Makefile
Labels: improvement
